version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/backend
  - source: server_configs/nginx/f2game.conf
    destination: /etc/nginx/sites-available/
    runas: ubuntu
  - source: server_configs/systemctl/gunicorn.service
    destination: /etc/systemd/system/
    runas: ubuntu
  - source: server_configs/cron.d/
    destination: /etc/cron.d
    runas: root
permissions:
  - object: /etc/cron.d
    pattern: "*"
    owner: root
    group: root
    mode: 644
    type:
      - file
hooks:
  BeforeInstall:
      - location: server_configs/scripts/before_install.sh
  AfterInstall:
      - location: server_configs/scripts/after_install.sh
